select * from PETRESCUE ;

---QUERY-1--GET TOTAL COST OF ALL ANIMALS--
SELECT SUM(COST)AS SUM_OF_COST FROM PETRESCUE;

---QUERY-2--GET MAX QUANTITY OF ANIMALS---
SELECT MAX(QUANTITY) AS MAX_QUANTITY FROM PETRESCUE;

---QUERY-3--GET AVERAGE COST OF ANIMALS--
SELECT AVG(COST) AS AVG_COST FROM PETRESCUE;

---QUERY-4--GET AVERAGE COST OF DOGS---
SELECT AVG(COST) AS AVG_COST FROM PETRESCUE
WHERE ANIMAL = 'Dog';

---QUERY-5--GET ROUNDED COST OF EACH ANIMAL--
SELECT ANIMAL , ROUND(COST) AS APPROX_COST 
FROM PETRESCUE;

---QUERY-6--GET LENGTH OF EACH ANIMAL---
SELECT ANIMAL, LENGTH(ANIMAL) AS ANIMAL_LEN
FROM PETRESCUE;

---QUERY-7--GET ANIMAL NAME IN UPPERCASE--
SELECT UCASE(ANIMAL) FROM PETRESCUE;

---QUERY-8--GET ALL THE RECORDS OF CAT--
SELECT * FROM PETRESCUE
WHERE LCASE(ANIMAL) = 'cat';

---QUERY-9--GET the day of the month when cats have been rescued--
SELECT DAY(RESCUEDATE) as RESCUE_DAY_FOR_CAT FROM PETRESCUE
WHERE ANIMAL = 'Cat';

---QUERY-10--GET the number of rescues on the 5th month--
SELECT SUM(QUANTITY) FROM PETRESCUE
WHERE MONTH(RESCUEDATE) = '05';

---QUERY-11--GET THE NUMBER RESCUE ON 14TH DAY OF MONTH--
SELECT SUM(QUANTITY) FROM PETRESCUE
WHERE DAY(RESCUEDATE) = '14';

---QUERY-12--GET THE THIRD DAY FROM EACH RESCUE--
SELECT (RESCUEDATE + 3 DAYS) FROM PETRESCUE;

---QUERY-13--GET THE DURATION OF TIME THE ANIMAL HAVE FROM RESCUE DATE--
SELECT ANIMAL, (RESCUEDATE - CURRENT_DATE) AS TIME_DURATION
FROM PETRESCUE;






